steps:
  # 🧪 Step 0: Print substitution values (for debugging)
  - name: 'ubuntu'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "NEXT_PUBLIC_TEST_VAR=${_NEXT_PUBLIC_TEST_VAR}"
        echo "NEXT_PUBLIC_API_URL=${_NEXT_PUBLIC_API_URL}"
        echo "✅ Substitution check complete."
    automapSubstitutions: true

  # 🏗️ Step 1: Build Docker image with build args
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'asia-south1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/ujjivan-vehicle-finance-dashboard-gcp/ujjivan-vehicle-finance-dashboard-gcp:$SHORT_SHA',
        '-t',
        'asia-south1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/ujjivan-vehicle-finance-dashboard-gcp/ujjivan-vehicle-finance-dashboard-gcp:latest',
        '--build-arg=NEXT_PUBLIC_TEST_VAR=${_NEXT_PUBLIC_TEST_VAR}',
        '--build-arg=NEXT_PUBLIC_API_URL=${_NEXT_PUBLIC_API_URL}',
        '--build-arg=BUILDKIT_INLINE_CACHE=1',
        '--cache-from',
        'asia-south1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/ujjivan-vehicle-finance-dashboard-gcp/ujjivan-vehicle-finance-dashboard-gcp:latest',
        '.'
      ]

  # 📦 Step 2: Push image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        '--all-tags',
        'asia-south1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/ujjivan-vehicle-finance-dashboard-gcp/ujjivan-vehicle-finance-dashboard-gcp'
      ]

  # 🚀 Step 3: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      [
        'run',
        'deploy',
        'ujjivan-vehicle-finance-dashboard-gcp',
        '--image',
        'asia-south1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/ujjivan-vehicle-finance-dashboard-gcp/ujjivan-vehicle-finance-dashboard-gcp:latest',
        '--region',
        'asia-south1',
        '--platform',
        'managed',
        '--allow-unauthenticated',
        '--port',
        '8080',
        '--memory',
        '512Mi',
        '--set-env-vars',
        'NEXT_PUBLIC_TEST_VAR=${_NEXT_PUBLIC_TEST_VAR},NEXT_PUBLIC_API_URL=${_NEXT_PUBLIC_API_URL}'
      ]

# 🔧 Default substitution values (used if not overridden in trigger)
substitutions:
  _NEXT_PUBLIC_TEST_VAR: 'default-test-value'
  _NEXT_PUBLIC_API_URL: 'https://api-dev.example.com'

# 🪞 Images that will appear in the build history
images:
  - 'asia-south1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/ujjivan-vehicle-finance-dashboard-gcp/ujjivan-vehicle-finance-dashboard-gcp:$SHORT_SHA'
  - 'asia-south1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/ujjivan-vehicle-finance-dashboard-gcp/ujjivan-vehicle-finance-dashboard-gcp:latest'

# ⚙️ Build options
options:
  logging: CLOUD_LOGGING_ONLY
  automapSubstitutions: true
